# Generated by Django 5.2.5 on 2025-08-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_accountabilitypartner_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
