# Generated by Django 5.2.5 on 2025-08-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_activity_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deck',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='flashcards.deck'),
            preserve_default=False,
        ),
    ]
