# Generated by Django 5.2.5 on 2025-09-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_activity_deck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountabilityPartner',
        ),
    ]
