# Generated by Django 5.2.5 on 2025-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_shop', '0002_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
