# Generated by Django 5.2.5 on 2025-08-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_shop', '0003_listing_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='listings', to='deck_shop.tag'),
        ),
    ]
