# Generated by Django 5.2 on 2025-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_tag_deck_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='numero_de_cards',
            field=models.IntegerField(default=0),
        ),
    ]
