# Generated by Django 5.2 on 2025-05-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_deck_numero_de_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
