# Generated by Django 5.2 on 2025-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_card_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagem_de_perfil',
            field=models.URLField(blank=True, default='https://static.vecteezy.com/system/resources/previews/013/360/247/non_2x/default-avatar-photo-icon-social-media-profile-sign-symbol-vector.jpg', null=True),
        ),
    ]
