# Generated by Django 5.2 on 2025-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_user_imagem_de_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='ordem_dos_cards',
            field=models.JSONField(default={'order': []}),
        ),
    ]
