# Generated by Django 5.2 on 2025-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_deck_ordem_dos_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='ordem_dos_cards',
            field=models.JSONField(default={'ordem': []}),
        ),
    ]
