# Generated by Django 5.2.1 on 2025-05-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_alter_deck_ordem_dos_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='ordem_dos_cards',
            field=models.JSONField(default={'ordem': []}),
        ),
    ]
