# Generated by Django 5.2 on 2025-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_alter_deck_ordem_dos_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='ordem_dos_cards',
            field=models.JSONField(default={'ordem': []}, verbose_name=dict),
        ),
    ]
