# Generated by Django 5.2 on 2025-06-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_alter_deck_ordem_dos_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
